nginx final release v1.11.7
- release version number tracks nginx's version
- caveat: downgrade in version number from 4 to 1.11.7 may cause
  problems
- upgrade nginx from 1.11.1 to 1.11.7
- add IPv6/gunzip/http_v2 module support
- removed nginx-upload-module-2.2
  - hasn't been updated since
    ['08](https://github.com/vkholodkov/nginx-upload-module)
  - won't [compile easily for nginx
    1.11.2+](https://github.com/vkholodkov/nginx-upload-module/issues/79)
  - was included for GoCD front-end, which has long since been
    abandoned.

fixes:
```
../nginx-upload-module-2.2/ngx_http_upload_module.c:14:17: fatal error:
md5.h: No such file or directory
 #include <md5.h>
                  ^
compilation terminated.
make[1]: ***
[objs/addon/nginx-upload-module-2.2/ngx_http_upload_module.o]
Error 1
```